### ISSUE TITLE
Improve "about" section on the repository GitHub page

### ISSUE THREAD

**Issue by natema** [worlddynamics/Vensim2MTK.jl#23]
The current about section should concisely present the package.

**Comment by natema** [comment]
Can you check this? I still see the old description.

**Comment by natema** [comment]
(And the link to MTK is not correctly formatted, so it is probably not supported and we shouldn't use the link then.)

**Comment by meyde** [comment]
is it visible now? i see it fine on my end

**Comment by meyde** [comment]
![Capture d’écran 2023-07-20 145153](https://github.com/worlddynamics/Vensim2MTK.jl/assets/59982953/045e80de-b1f7-401f-9167-b6c58602b54c)


are we not talking about this?

**Comment by meyde** [comment]
i.. did not see the correction, i thought it was just a citation, i'm really sorry!

**Comment by meyde** [comment]
i corrected it..
