### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by natema** [worlddynamics/Vensim2MTK.jl#27]
I tagged the registrator bot here: https://github.com/worlddynamics/Vensim2MTK.jl/commit/071e0c9601123fcf3dcc83f675724d9c5306dd37#commitcomment-122178500

**Comment by natema** [comment]
Succeeded: https://github.com/worlddynamics/Vensim2MTK.jl/commit/eb081a72cb065d5645c009f93e51531faf70af3d#commitcomment-122179188 .

**Comment by natema** [comment]
I fixed the missing `[compat]` and now Registrator is trying again: https://github.com/JuliaRegistries/General/pull/87862

**Comment by natema** [comment]
Everything seems fine, let's wait and see.

**Comment by natema** [comment]
The [Registrator says](https://github.com/JuliaRegistries/General/pull/87862#issuecomment-1643673778)
> Your new package pull request met all of the guidelines for auto-merging and is scheduled to be merged when the mandatory waiting period (3 days) has elapsed.

**Comment by meyde** [comment]
great!

**Comment by natema** [comment]
There is some problem, which I don't understand: #31 .
I'll try creating a tag for the first version manually.

**Comment by natema** [comment]
It seems that in a couple of hours TagBot will look again for the tag of the release (which know exists).

**Comment by natema** [comment]
I tested on a couple of machines and one can already correctly install the package by issuing `add Vensim2MTK` in package mode from the REPL.

**Comment by meyde** [comment]
that's a good news, right? is the tagbot issue fixed then?

**Comment by natema** [comment]
Kind of. The tagbot stopped complaining, but we are missing the "release" in the repo (cfr. with other repos). Apparently it didn't get created automatically.

**Comment by meyde** [comment]
so should we create it manually? how would that be done?

**Comment by natema** [comment]
I think we should; we should look for how to do it.

**Comment by natema** [comment]
I did it. In the end one just need to press a couple of buttons. 
We can close this. 

OT: Feel free to create a PR from dev to main when the branch is ready to be merged.
