### ISSUE TITLE
Misspelled name of model

### ISSUE THREAD

**Issue by rogersamso** [worlddynamics/Vensim2MTK.jl#35]
Hi,

I was having issues importing the Lotka-Volterra model, until I found it is actually misspelled. Instead of `lokta.xmile`, it should be `lotka.xmile`.

**Comment by natema** [comment]
Thanks again! The package is still quite experimental and came out from a student internship, so it didn't undergo much testing.

**Comment by rogersamso** [comment]
I see! Looks very promising! I am a contributor to the pysd library, and I have for long hoped that somebody would come up with a similar solution in julia!

Do you have plans to continue with the development of the library in the short-mid term?

BTW, the lotka-Volterra model is also misspelled in the README.

**Comment by natema** [comment]
Thanks, it is motivating to see people interested in the project. Unfortunately, plans at the moment are uncertain, as the efforts on [the overall project](https://github.com/worlddynamics/WorldDynamics.jl) do not seem to have elicited the interest we expected.
